In [ ]:
import pandas as pd

In [ ]:
file_path = "/content/SuperStore_Sales_Dataset_Raw.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully!
Shape: (5901, 23)

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode,ind1,ind2
0,4918,CA-2019-160304,01-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.94,1,28.2668,NaN,Online,NaN,NaN
1,4919,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.94,3,38.2668,NaN,Online,NaN,NaN
2,4920,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Technology,Phones,GE 30522EE2,231.98,2,67.2742,NaN,Cards,NaN,NaN
3,3074,CA-2019-125206,03-01-2019,05-01-2019,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,...,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.46,2,28.6150,NaN,Online,NaN,NaN
4,8604,US-2019-116365,03-01-2019,08-01-2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.08,2,-5.2640,NaN,Online,NaN,NaN

In [ ]:
print("Dataset Information:\n")
df.info()

print("\nFirst 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

Dataset Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5901 entries, 0 to 5900
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row ID+O6G3A1:R6  5901 non-null   int64
 1   Order ID          5901 non-null   object
 2   Order Date        5901 non-null   object
 3   Ship Date         5901 non-null   object
 4   Ship Mode         5901 non-null   object
 5   Customer ID       5901 non-null   object
 6   Customer Name     5901 non-null   object
 7   Segment           5901 non-null   object
 8   Country           5901 non-null   object
 9   City              5901 non-null   object
 10  State             5901 non-null   object
 11  Region            5901 non-null   object
 12  Product ID        5901 non-null   object
 13  Category          5901 non-null   object
 14  Sub-Category      5901 non-null   object
 15  Product Name      5901 non-null   object
 16  Sales             5901 non-null   float64
 17  Quantity          5901 non-null   int64
 18  Profit            5901 non-null   float64
 19  Returns           287 non-null    float64
 20  Payment Mode      5901 non-null   object
 21  ind1              0 non-null      float64
 22  ind2              0 non-null      float64
dtypes: float64(5), int64(2), object(16)
memory usage: 1.0+ MB

First 5 Rows:

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode,ind1,ind2
0,4918,CA-2019-160304,01-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.94,1,28.2668,NaN,Online,NaN,NaN
1,4919,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.94,3,38.2668,NaN,Online,NaN,NaN
2,4920,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Technology,Phones,GE 30522EE2,231.98,2,67.2742,NaN,Cards,NaN,NaN
3,3074,CA-2019-125206,03-01-2019,05-01-2019,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,...,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.46,2,28.6150,NaN,Online,NaN,NaN
4,8604,US-2019-116365,03-01-2019,08-01-2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.08,2,-5.2640,NaN,Online,NaN,NaN

Last 5 Rows:

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode,ind1,ind2
5896,907,CA-2020-143259,30-12-2020,03-01-2021,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Fully Ass...",213.136,4,12.1176,NaN,COD,NaN,NaN
5897,1297,CA-2020-115427,30-12-2020,03-01-2021,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",295.904,2,4.5188,1.0,Online,NaN,NaN
5898,5092,CA-2020-156720,30-12-2020,03-01-2021,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,Office Supplies,Fasteners,Bagged Rubber Bands,388.024,3,-0.6048,NaN,Online,NaN,NaN
5899,909,CA-2020-143259,30-12-2020,03-01-2021,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,462.776,3,19.7910,NaN,COD,NaN,NaN
5900,5093,CA-2020-151450,31-12-2020,04-01-2021,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,Office Supplies,Fasteners,Bagged Rubber Bands,2975.510,3,-0.6048,NaN,COD,NaN,NaN

In [ ]:
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Number of Rows: 5901
Number of Columns: 23

In [ ]:
df.columns = df.columns.str.strip()

df.rename(
    columns={
        "Row ID+O6G3A1:R6": "Row ID"
    },
    inplace=True
)

print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Profit', 'Returns', 'Payment Mode', 'ind1', 'ind2']

In [ ]:
missing_values = df.isnull().sum()

print("Missing Values:")
print(missing_values[missing_values > 0])

Missing Values:
Returns    5614
ind1       5901
ind2       5901
dtype: int64

In [ ]:
df.drop(
    columns=["ind1", "ind2"],
    inplace=True
)

In [ ]:
print(df.columns.tolist())
print("New shape:", df.shape)

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Profit', 'Returns', 'Payment Mode']
New shape: (5901, 21)

In [ ]:
df["Return Status"] = df["Returns"].apply(
    lambda x: "Returned" if x == 1 else "Not Returned"
)

In [ ]:
print(df["Return Status"].value_counts())

Return Status
Not Returned    5614
Returned         287
Name: count, dtype: int64

In [ ]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [ ]:
df.drop_duplicates(inplace=True)

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (5901, 22)

In [ ]:
print("Unique Order IDs:", df["Order ID"].nunique())
print("Total Rows:", len(df))

Unique Order IDs: 3003
Total Rows: 5901

In [ ]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [ ]:
print(df[["Order Date", "Ship Date"]].dtypes)

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

In [ ]:
print(df[["Order Date", "Ship Date"]].isnull().sum())

Order Date    0
Ship Date     0
dtype: int64

In [ ]:
invalid_dates = df[
    df["Ship Date"] < df["Order Date"]
]

print("Invalid Shipping Date Records:")
print(len(invalid_dates))

Invalid Shipping Date Records:
0

In [ ]:
df["Shipping Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

In [ ]:
df[[
    "Order Date",
    "Ship Date",
    "Shipping Days"
]].head()

  Order Date  Ship Date  Shipping Days
0 2019-01-01 2019-01-07              6
1 2019-01-02 2019-01-07              5
2 2019-01-02 2019-01-07              5
3 2019-01-03 2019-01-05              2
4 2019-01-03 2019-01-08              5

In [ ]:
numeric_columns = [
    "Sales",
    "Quantity",
    "Profit",
    "Shipping Days"
]

print(df[numeric_columns].describe())

             Sales     Quantity       Profit  Shipping Days
count  5901.000000  5901.000000  5901.000000    5901.000000
mean    265.345589     3.781901    29.700408       3.926962
std     474.260645     2.212917   259.589138       1.792050
min       0.836000     1.000000 -6599.978000       0.000000
25%      71.976000     2.000000     1.795500       3.000000
50%     128.648000     3.000000     8.502500       4.000000
75%     265.170000     5.000000    28.615000       5.000000
max    9099.930000    14.000000  8399.976000       8.000000

In [ ]:
invalid_sales = df[df["Sales"] <= 0]

print("Invalid Sales Records:", len(invalid_sales))
display(invalid_sales.head())

Invalid Sales Records: 0

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Profit, Returns, Payment Mode, Return Status, Shipping Days]
Index: []

[0 rows x 23 columns]

In [ ]:
negative_profit = df[df["Profit"] < 0]

print("Negative Profit Records:", len(negative_profit))

display(
    negative_profit[
        [
            "Order ID",
            "Product Name",
            "Category",
            "Sales",
            "Profit"
        ]
    ].head()
)

Negative Profit Records: 1098

,Order ID,Product Name,Category,Sales,Profit
4,US-2019-116365,Imation Clip USB flash drive - 8 GB,Technology,30.080,-5.2640
5,US-2019-116365,WD My Passport Ultra 1TB Portable External Har...,Technology,165.600,-6.2100
11,CA-2019-158211,Avery Arch Ring Binders,Office Supplies,104.580,-80.1780
16,CA-2019-158806,"Executive Impressions 13"" Clairmont Wall Clock",Furniture,23.076,-10.9611
20,US-2019-137295,"XtraLife ClearVue Slant-D Ring Binder, White, 3""",Office Supplies,30.828,-24.6624

In [ ]:
print("Sales Outliers:")
print(df["Sales"].describe())

print("\nProfit Outliers:")
print(df["Profit"].describe())

print("\nQuantity:")
print(df["Quantity"].describe())

Sales Outliers:
count    5901.000000
mean      265.345589
std       474.260645
min         0.836000
25%        71.976000
50%       128.648000
75%       265.170000
max      9099.930000
Name: Sales, dtype: float64

Profit Outliers:
count    5901.000000
mean       29.700408
std       259.589138
min     -6599.978000
25%         1.795500
50%         8.502500
75%        28.615000
max      8399.976000
Name: Profit, dtype: float64

Quantity:
count    5901.000000
mean        3.781901
std         2.212917
min         1.000000
25%         2.000000
50%         3.000000
75%         5.000000
max        14.000000
Name: Quantity, dtype: float64

In [ ]:
categorical_columns = [
    "Ship Mode",
    "Segment",
    "Country",
    "Region",
    "Category",
    "Sub-Category",
    "Payment Mode",
    "Return Status"
]

for column in categorical_columns:
    print("\n" + "=" * 50)
    print(column)
    print(df[column].value_counts())

==================================================
Ship Mode
Ship Mode
Standard Class    3451
Second Class      1147
First Class        959
Same Day           344
Name: count, dtype: int64

==================================================
Segment
Segment
Consumer       2997
Corporate      1774
Home Office    1130
Name: count, dtype: int64

==================================================
Country
Country
United States    5901
Name: count, dtype: int64

==================================================
Region
Region
West       1901
East       1688
Central    1381
South       931
Name: count, dtype: int64

==================================================
Category
Category
Office Supplies    3569
Furniture          1249
Technology         1083
Name: count, dtype: int64

==================================================
Sub-Category
Sub-Category
Binders        915
Paper          825
Furnishings    573
Phones         519
Storage        498
Art            465
Accessories    461
Chairs         355
Appliances     279
Labels         211
Tables         190
Envelopes      133
Bookcases      131
Fasteners      124
Supplies       119
Machines        65
Copiers         38
Name: count, dtype: int64

==================================================
Payment Mode
Payment Mode
COD       2453
Online    2164
Cards     1284
Name: count, dtype: int64

==================================================
Return Status
Return Status
Not Returned    5614
Returned         287
Name: count, dtype: int64

In [ ]:
text_columns = df.select_dtypes(
    include="object"
).columns

for column in text_columns:
    df[column] = df[column].astype(str).str.strip()

In [ ]:
text_columns = df.select_dtypes(
    include="object"
).columns

for column in text_columns:
    df[column] = df[column].astype(str).str.strip()

In [ ]:
df["Year"] = df["Order Date"].dt.year

df["Month Number"] = df["Order Date"].dt.month

df["Month"] = df["Order Date"].dt.month_name()

df["Month Year"] = df["Order Date"].dt.to_period("M").astype(str)

In [ ]:
df[
    [
        "Order Date",
        "Year",
        "Month Number",
        "Month",
        "Month Year"
    ]
].head()

  Order Date  Year  Month Number    Month Month Year
0 2019-01-01  2019             1  January    2019-01
1 2019-01-02  2019             1  January    2019-01
2 2019-01-02  2019             1  January    2019-01
3 2019-01-03  2019             1  January    2019-01
4 2019-01-03  2019             1  January    2019-01

In [ ]:
df["Profit Margin %"] = (
    df["Profit"] / df["Sales"] * 100
)

In [ ]:
df["Profit Margin %"] = df[
    "Profit Margin %"
].round(2)

In [ ]:
df[
    [
        "Sales",
        "Profit",
        "Profit Margin %"
    ]
].head()

    Sales   Profit  Profit Margin %
0   73.94  28.2668            38.23
1  173.94  38.2668            22.00
2  231.98  67.2742            29.00
3  114.46  28.6150            25.00
4   30.08  -5.2640           -17.50

In [ ]:
print("Final Missing Values:")
print(
    df.isnull().sum()[
        df.isnull().sum() > 0
    ]
)

Final Missing Values:
Returns    5614
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5901 entries, 0 to 5900
Data columns (total 28 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Row ID           5901 non-null   int64
 1   Order ID         5901 non-null   object
 2   Order Date       5901 non-null   datetime64[ns]
 3   Ship Date        5901 non-null   datetime64[ns]
 4   Ship Mode        5901 non-null   object
 5   Customer ID      5901 non-null   object
 6   Customer Name    5901 non-null   object
 7   Segment          5901 non-null   object
 8   Country          5901 non-null   object
 9   City             5901 non-null   object
 10  State            5901 non-null   object
 11  Region           5901 non-null   object
 12  Product ID       5901 non-null   object
 13  Category         5901 non-null   object
 14  Sub-Category     5901 non-null   object
 15  Product Name     5901 non-null   object
 16  Sales            5901 non-null   float64
 17  Quantity         5901 non-null   int64
 18  Profit           5901 non-null   float64
 19  Returns          287 non-null    float64
 20  Payment Mode     5901 non-null   object
 21  Return Status    5901 non-null   object
 22  Shipping Days    5901 non-null   int64
 23  Year             5901 non-null   int32
 24  Month Number     5901 non-null   int32
 25  Month            5901 non-null   object
 26  Month Year       5901 non-null   object
 27  Profit Margin %  5901 non-null   float64
dtypes: datetime64[ns](2), float64(4), int32(2), int64(3), object(17)
memory usage: 1.2+ MB

In [ ]:
import os

output_file = "/mnt/data/SuperStore_Sales_Dataset_Cleaned.csv"

# Extract the directory path
output_dir = os.path.dirname(output_file)

# Create the directory if it doesn't exist
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
    print(f"Created directory: {output_dir}")

df.to_csv(
    output_file,
    index=False
)

print("Cleaned dataset saved successfully!")
print(output_file)

Created directory: /mnt/data
Cleaned dataset saved successfully!
/mnt/data/SuperStore_Sales_Dataset_Cleaned.csv